import { NextRequest, NextResponse } from 'next/server'
import { cookies } from 'next/headers'
import { supabaseAdmin } from '@/lib/supabaseAdmin'
import { resolveClinicContext } from '@/lib/clinic'
import { z } from 'zod'

export const dynamic = 'force-dynamic'

const quoteItemSchema = z.object({
  service_id: z.string().uuid().optional().nullable(),
  service_name: z.string().min(1).max(255),
  service_description: z.string().optional().nullable(),
  quantity: z.number().int().min(1).default(1),
  unit_price_cents: z.number().int().min(0),
  discount_type: z.enum(['none', 'percentage', 'fixed']).default('none'),
  discount_value: z.number().min(0).default(0),
  tooth_number: z.string().max(10).optional().nullable(),
  notes: z.string().optional().nullable(),
  sort_order: z.number().int().default(0),
})

const quoteSchema = z.object({
  patient_id: z.string().uuid(),
  quote_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  validity_days: z.number().int().min(1).max(365).default(30),
  discount_type: z.enum(['none', 'percentage', 'fixed']).default('none'),
  discount_value: z.number().min(0).default(0),
  tax_rate: z.number().min(0).max(100).default(0),
  notes: z.string().optional().nullable(),
  patient_notes: z.string().optional().nullable(),
  terms_conditions: z.string().optional().nullable(),
  items: z.array(quoteItemSchema).min(1, 'At least one service is required'),
})

/**
 * GET /api/quotes
 * Fetch quotes with optional filters
 */
export async function GET(request: NextRequest): Promise<NextResponse> {
  try {
    const cookieStore = await cookies()
    const searchParams = request.nextUrl.searchParams

    const clinicContext = await resolveClinicContext({
      requestedClinicId: searchParams.get('clinicId'),
      cookieStore,
    })

    if ('error' in clinicContext) {
      return NextResponse.json(
        { error: clinicContext.error.message },
        { status: clinicContext.error.status }
      )
    }

    const { clinicId } = clinicContext

    // Get query params
    const patientId = searchParams.get('patientId')
    const status = searchParams.get('status')
    const startDate = searchParams.get('startDate')
    const endDate = searchParams.get('endDate')

    // Build query
    let query = supabaseAdmin
      .from('quotes')
      .select(`
        *,
        patient:patients(id, first_name, last_name, email, phone),
        items:quote_items(*)
      `)
      .eq('clinic_id', clinicId)
      .order('quote_date', { ascending: false })

    if (patientId) {
      query = query.eq('patient_id', patientId)
    }

    if (status) {
      query = query.eq('status', status)
    }

    if (startDate) {
      query = query.gte('quote_date', startDate)
    }

    if (endDate) {
      query = query.lte('quote_date', endDate)
    }

    const { data, error } = await query

    if (error) {
      console.error('[Quotes] Error fetching:', error)
      return NextResponse.json({ error: error.message }, { status: 500 })
    }

    return NextResponse.json({ data })
  } catch (error) {
    console.error('[Quotes] Unexpected error:', error)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}

/**
 * POST /api/quotes
 * Create a new quote with items
 */
export async function POST(request: NextRequest): Promise<NextResponse> {
  try {
    const cookieStore = await cookies()
    const body = await request.json()

    const clinicContext = await resolveClinicContext({
      requestedClinicId: body.clinic_id,
      cookieStore,
    })

    if ('error' in clinicContext) {
      return NextResponse.json(
        { error: clinicContext.error.message },
        { status: clinicContext.error.status }
      )
    }

    const { clinicId, userId } = clinicContext

    // Validate input
    const validation = quoteSchema.safeParse(body)
    if (!validation.success) {
      return NextResponse.json(
        { error: 'Validation failed', details: validation.error.errors },
        { status: 400 }
      )
    }

    const { items, ...quoteData } = validation.data

    // Verify patient belongs to clinic
    const { data: patient, error: patientError } = await supabaseAdmin
      .from('patients')
      .select('id')
      .eq('id', quoteData.patient_id)
      .eq('clinic_id', clinicId)
      .single()

    if (patientError || !patient) {
      return NextResponse.json({ error: 'Patient not found' }, { status: 404 })
    }

    // Create quote (quote_number and valid_until auto-generated by triggers)
    const { data: quote, error: quoteError } = await supabaseAdmin
      .from('quotes')
      .insert({
        clinic_id: clinicId,
        created_by: userId,
        status: 'draft',
        ...quoteData,
      })
      .select()
      .single()

    if (quoteError) {
      console.error('[Quotes] Error creating:', quoteError)
      return NextResponse.json({ error: quoteError.message }, { status: 500 })
    }

    // Create quote items (totals auto-calculated by triggers)
    const itemsToInsert = items.map((item, index) => ({
      quote_id: quote.id,
      ...item,
      sort_order: item.sort_order ?? index,
      // These will be calculated by trigger, but we need to provide them
      subtotal_cents: item.quantity * item.unit_price_cents,
      total_cents: item.quantity * item.unit_price_cents, // Trigger will adjust for discounts
    }))

    const { error: itemsError } = await supabaseAdmin
      .from('quote_items')
      .insert(itemsToInsert)

    if (itemsError) {
      console.error('[Quotes] Error creating items:', itemsError)
      // Rollback quote
      await supabaseAdmin.from('quotes').delete().eq('id', quote.id)
      return NextResponse.json({ error: itemsError.message }, { status: 500 })
    }

    // Fetch complete quote with items and updated totals
    const { data: completeQuote, error: fetchError } = await supabaseAdmin
      .from('quotes')
      .select(`
        *,
        patient:patients(id, first_name, last_name, email, phone),
        items:quote_items(*)
      `)
      .eq('id', quote.id)
      .single()

    if (fetchError) {
      return NextResponse.json({ data: quote }, { status: 201 })
    }

    return NextResponse.json({ data: completeQuote }, { status: 201 })
  } catch (error) {
    console.error('[Quotes] Unexpected error:', error)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
